name: Run NodeJS tests on a Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with: 
          mongodb-version: 5.0.2
      
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6.2.5
      
      - name: npm install and test
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          npm ci
          npm run test
